import type { CmsPage } from '@/schemas/blocks';

export const mockPages: CmsPage[] = [
  {
    slug: 'home',
    locale: 'en',
    blocks: [
      {
        type: 'hero-intent',
        title: "Banking that grows with Sudan's economy.",
        subtitle: 'Empowering exporters and local industries with innovative financial solutions, global trade expertise, and digital-first banking tools.',
        primaryCta: { label: 'Open Account', href: '/en/retail-banking' },
        secondaryCta: { label: 'Trade Finance', href: '/en/corporate-banking' },
      },
      {
        type: 'trust-metrics',
        eyebrow: 'Our Numbers Speak',
        title: 'Trusted by Individuals and Businesses',
        metrics: [
          { label: 'Customers', value: '1.2M+', note: 'Retail and corporate clients' },
          { label: 'Branches', value: '62', note: 'Across Sudan' },
          { label: 'ATMs', value: '280+', note: '24/7 access points' },
          { label: 'Total Assets', value: '$3.4B', note: 'Strong and resilient growth' },
        ],
      },
      {
        type: 'fx-rates',
        title: 'FX Rates',
        liveLabel: 'Live',
        rates: [
          {
            pair: 'USD/SDG',
            trend: 'up',
            change: '0.12%',
            buyLabel: 'Buy',
            sellLabel: 'Sell',
            buy: '584.20',
            sell: '588.50',
          },
          {
            pair: 'EUR/SDG',
            trend: 'down',
            change: '0.08%',
            buyLabel: 'Buy',
            sellLabel: 'Sell',
            buy: '632.15',
            sell: '636.80',
          },
          {
            pair: 'SAR/SDG',
            trend: 'up',
            change: '0.05%',
            buyLabel: 'Buy',
            sellLabel: 'Sell',
            buy: '155.70',
            sell: '157.00',
          },
          {
            pair: 'AED/SDG',
            trend: 'flat',
            change: '0.00%',
            buyLabel: 'Buy',
            sellLabel: 'Sell',
            buy: '159.05',
            sell: '160.25',
          },
        ],
      },
      {
        type: 'quick-actions',
        title: 'Quick Actions',
        actions: [
          { label: 'Transfers', href: '/en/services' },
          { label: 'Bill Payments', href: '/en/services' },
          { label: 'Cards', href: '/en/services' },
          { label: 'Foreign Exchange', href: '/en/services' },
        ],
      },
      {
        type: 'announcement-rail',
        title: 'Product Navigator',
        items: [
          {
            id: 'a1',
            category: 'Export Finance',
            headline: 'Pre-shipment financing',
            excerpt: 'Specialized working capital solutions for Sudanese exporters to facilitate global trade operations.',
            href: '/en/corporate-banking',
          },
          {
            id: 'a2',
            category: 'Savings Plus',
            headline: 'High yield returns',
            excerpt: "Grow your wealth with Sudan's most competitive profit rates on savings accounts and fixed deposits.",
            href: '/en/retail-banking',
          },
          {
            id: 'a3',
            category: 'Visa Signature',
            headline: 'Global lounge access',
            excerpt: 'Elite lifestyle benefits and global lounge access. Designed for the frequent business traveler.',
            href: '/en/offers-rewards',
          },
        ],
      },
      {
        type: 'latest-news',
        title: 'Latest News',
        eyebrow: 'Announcements',
        viewAllLabel: 'View All',
        items: [
          {
            id: 'n1',
            date: 'OCT 24, 2023',
            title: 'EDB Sudan Expands Digital Trade Finance Support',
            excerpt: 'New integrated digital platform streamlines credit facilities for exporters across agricultural sectors.',
            href: '/en/announcements-hub',
            cta: 'Read More',
          },
          {
            id: 'n2',
            date: 'OCT 18, 2023',
            title: 'Strategic Partnership for Local Industrial Growth',
            excerpt: 'Collaboration with local manufacturers to provide specialized equipment leasing and financing solutions.',
            href: '/en/announcements-hub',
            cta: 'Read More',
          },
          {
            id: 'n3',
            date: 'OCT 12, 2023',
            title: 'Enhanced Security Measures for Online Banking',
            excerpt: 'EDB introduces multi-layer biometric authentication for all corporate digital transactions and treasury tools.',
            href: '/en/announcements-hub',
            cta: 'Read More',
          },
        ],
      },
      {
        type: 'mobile-app-promo',
        eyebrow: 'Mobile Application',
        title: 'Bank on the Go',
        description: 'Experience banking without boundaries. Our mobile app provides secure transactions, fast processing, and complete control over your finances.',
        features: ['Secure biometric login', 'Instant local and international transfers', 'Card controls and spending insights'],
        appStoreLabel: 'App Store',
        appStoreSubLabel: 'Download on the',
        playStoreLabel: 'Google Play',
        playStoreSubLabel: 'Get it on',
        qrLabel: 'Scan to Download',
      },
    ],
  },
  {
    slug: 'home',
    locale: 'ar',
    blocks: [
      {
        type: 'hero-intent',
        title: 'خدمات مصرفية تدعم نمو اقتصاد السودان.',
        subtitle: 'نمكّن المصدرين والصناعات المحلية عبر حلول مالية مبتكرة وخبرة واسعة في التجارة العالمية وأدوات رقمية حديثة.',
        primaryCta: { label: 'افتح حساب', href: '/ar/retail-banking' },
        secondaryCta: { label: 'تمويل التجارة', href: '/ar/corporate-banking' },
      },
      {
        type: 'trust-metrics',
        eyebrow: 'أرقامنا تتحدث',
        title: 'ثقة الأفراد والشركات',
        metrics: [
          { label: 'العملاء', value: '+1.2M', note: 'عملاء الأفراد والشركات' },
          { label: 'الفروع', value: '62', note: 'في مختلف أنحاء السودان' },
          { label: 'أجهزة الصراف', value: '+280', note: 'خدمة على مدار الساعة' },
          { label: 'إجمالي الأصول', value: '$3.4B', note: 'نمو قوي ومستدام' },
        ],
      },
      {
        type: 'fx-rates',
        title: 'أسعار الصرف',
        liveLabel: 'مباشر',
        rates: [
          {
            pair: 'USD/SDG',
            trend: 'up',
            change: '0.12%',
            buyLabel: 'شراء',
            sellLabel: 'بيع',
            buy: '584.20',
            sell: '588.50',
          },
          {
            pair: 'EUR/SDG',
            trend: 'down',
            change: '0.08%',
            buyLabel: 'شراء',
            sellLabel: 'بيع',
            buy: '632.15',
            sell: '636.80',
          },
          {
            pair: 'SAR/SDG',
            trend: 'up',
            change: '0.05%',
            buyLabel: 'شراء',
            sellLabel: 'بيع',
            buy: '155.70',
            sell: '157.00',
          },
          {
            pair: 'AED/SDG',
            trend: 'flat',
            change: '0.00%',
            buyLabel: 'شراء',
            sellLabel: 'بيع',
            buy: '159.05',
            sell: '160.25',
          },
        ],
      },
      {
        type: 'quick-actions',
        title: 'إجراءات سريعة',
        actions: [
          { label: 'التحويلات', href: '/ar/services' },
          { label: 'سداد الفواتير', href: '/ar/services' },
          { label: 'البطاقات', href: '/ar/services' },
          { label: 'العملات الأجنبية', href: '/ar/services' },
        ],
      },
      {
        type: 'announcement-rail',
        title: 'مستكشف المنتجات',
        items: [
          {
            id: 'a1',
            category: 'تمويل الصادرات',
            headline: 'تمويل ما قبل الشحن',
            excerpt: 'حلول رأس مال عامل للمصدرين السودانيين لتسهيل عمليات التجارة العالمية.',
            href: '/ar/corporate-banking',
          },
          {
            id: 'a2',
            category: 'التوفير بلس',
            headline: 'عائدات تنافسية',
            excerpt: 'نمِّ مدخراتك عبر معدلات ربح تنافسية على حسابات التوفير والودائع.',
            href: '/ar/retail-banking',
          },
          {
            id: 'a3',
            category: 'فيزا سيغنتشر',
            headline: 'دخول الصالات العالمية',
            excerpt: 'مزايا نخبوية ودخول صالات المطارات حول العالم للمسافر الدائم.',
            href: '/ar/offers-rewards',
          },
        ],
      },
      {
        type: 'latest-news',
        title: 'آخر الأخبار',
        eyebrow: 'الإعلانات',
        viewAllLabel: 'عرض الكل',
        items: [
          {
            id: 'n1',
            date: '24 أكتوبر 2023',
            title: 'بنك تنمية الصادرات يوسّع دعم تمويل التجارة الرقمية',
            excerpt: 'منصة رقمية متكاملة جديدة تُسرّع تسهيلات الائتمان للمصدرين في القطاعات الزراعية.',
            href: '/ar/announcements-hub',
            cta: 'اقرأ المزيد',
          },
          {
            id: 'n2',
            date: '18 أكتوبر 2023',
            title: 'شراكة استراتيجية لدعم نمو الصناعة المحلية',
            excerpt: 'تعاون مع المصنعين المحليين لتقديم حلول متخصصة للتمويل وتأجير المعدات.',
            href: '/ar/announcements-hub',
            cta: 'اقرأ المزيد',
          },
          {
            id: 'n3',
            date: '12 أكتوبر 2023',
            title: 'تعزيز إجراءات الأمان للخدمات المصرفية الرقمية',
            excerpt: 'إدخال مصادقة متعددة الطبقات للمعاملات الرقمية للشركات وخدمات الخزينة.',
            href: '/ar/announcements-hub',
            cta: 'اقرأ المزيد',
          },
        ],
      },
      {
        type: 'mobile-app-promo',
        eyebrow: 'تطبيق الهاتف',
        title: 'مصرفك في كل مكان',
        description: 'اختبر الخدمات المصرفية بلا حدود. يمنحك تطبيقنا معاملات آمنة، معالجة أسرع، وتحكمًا كاملاً في أموالك.',
        features: ['دخول آمن ببصمة الوجه أو الإصبع', 'تحويلات فورية محلية ودولية', 'تحكم كامل بالبطاقات ومتابعة المصروفات'],
        appStoreLabel: 'App Store',
        appStoreSubLabel: 'حمّله من',
        playStoreLabel: 'Google Play',
        playStoreSubLabel: 'احصل عليه من',
        qrLabel: 'امسح للتنزيل',
      },
    ],
  },
];
